-- simple_filt.vhd
-- Generated by PySys
-- Thu Jan  7 18:56:46 2010

library IEEE;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

library work;
use work.PySys_lib.all;

entity simple_filt is
	port (
		clk: in std_logic;
		rst: in std_logic;
		filt_in: in std_logic_vector(8 downto 0);
		filt_out: out std_logic_vector(18 downto 0));
end simple_filt;

architecture simple_filt_arch of simple_filt is 

-- Internal signals
--------------------------------------------------------------------------
signal filt_out_int: std_logic_vector(18 downto 0);
--------------------------------------------------------------------------

component fir_filt_s_comp
	 generic (n ,m: integer);
	 Port (
		clk: in std_logic;
		rst: in std_logic;
		filt_in: in std_logic_vector((n - 1) downto 0);
		filt_param: in std_logic_vector(((m * n) - 1) downto 0);
		filt_out: out std_logic_vector((filt_acc_bus(n, m) - 1) downto 0));
end component;


begin

     filt_out  <= filt_out_int;
     
       fir_filt_s_comp_U0: fir_filt_s_comp generic map(n => 9, m => 2)
       port map (
              clk => clk,
              rst => rst,
              filt_in => filt_in,
              filt_param => "111111011000110011",
              filt_out => filt_out_int);

end simple_filt_arch;